import { MeetingRoom, Booking, Hold } from '@/types/meeting-room';

export const mockRooms: MeetingRoom[] = [
  {
    id: '111',
    name: '111会议室新',
    group: '线上会议测试',
    location: '会议室楼宇/会议室1楼',
    capacity: 8,
    facilities: ['电视', '投影仪', '白板'],
    image: '/api/placeholder/200/150',
    isOpen: true,
    waterSign: '1台',
  },
  {
    id: '112',
    name: '112会议室新',
    group: '线上会议测试',
    location: '会议室楼宇/会议室1楼',
    capacity: 6,
    facilities: ['电视', '投影仪'],
    image: '/api/placeholder/200/150',
    isOpen: true,
  },
  {
    id: '109',
    name: '109会议',
    group: '线上会议测试',
    location: '会议室楼宇/会议室1楼',
    capacity: 10,
    facilities: ['电视', '电梯'],
    image: '/api/placeholder/200/150',
    isOpen: true,
  },
  {
    id: '110',
    name: '110会议',
    group: '线上会议测试',
    location: '会议室楼宇/会议室1楼',
    capacity: 10,
    facilities: ['电视', '电梯'],
    image: '/api/placeholder/200/150',
    isOpen: false,
  },
  {
    id: '3a-601-2',
    name: '3A-601-2 (头号玩家)',
    group: '建筑-楼层',
    location: '电视/白板/1楼',
    capacity: 8,
    facilities: ['电视', '投影仪', '白板'],
    image: '/api/placeholder/200/150',
    isOpen: true,
  },
  {
    id: '3a-601-3',
    name: '星际穿越 (3A-601-3)',
    group: '建筑-楼层',
    location: '电视/白板',
    capacity: 6,
    facilities: ['电视', '白板'],
    image: '/api/placeholder/200/150',
    isOpen: true,
  },
  {
    id: '3a-601-2-2',
    name: '复仇者联盟 (3B-601-2)',
    group: '建筑-楼层',
    location: '电视/白板',
    capacity: 10,
    facilities: ['电视', '白板'],
    image: '/api/placeholder/200/150',
    isOpen: true,
  },
];

export const mockBookings: Booking[] = [
  {
    id: 'b1',
    roomId: '3a-601-2',
    roomName: '3A-601-2 (头号玩家)',
    title: '会议室V1.0测试',
    startTime: new Date('2025-11-12T16:00:00'),
    endTime: new Date('2025-11-12T17:30:00'),
    participants: ['张三', '李四'],
    organizer: '当前用户',
    notificationTime: '15',
    isMyBooking: true,
  },
  {
    id: 'b2',
    roomId: '3a-601-2',
    roomName: '3A-601-2 (头号玩家)',
    title: '团队会议',
    startTime: new Date('2025-11-10T15:15:00'),
    endTime: new Date('2025-11-10T15:45:00'),
    participants: ['王五'],
    organizer: '其他用户',
    notificationTime: '15',
    isMyBooking: false,
  },
];

export const mockHolds: Hold[] = [];
